### ISSUE TITLE
How to mute mic

### ISSUE THREAD

**Issue by Fratm** [pschmitt/obs-cli#6]
Hi,  I have looked through the docs for this and cannot figure out a way to mute the mic using obs-cli.   Is there a way to do this?  I've tried setting things that made sense to me vi input set "Mic/Aux" but nothing seems to make a difference.

Thanks.

**Comment by pschmitt** [comment]
I don't do audio w/ OBS so I this just isn't implemented as of now. 

Looking at the obs-ws docs it seems that there is `SetInputMute` and `ToggleInputMute` (https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#setinputmute) which sounds like what you are after.

Shouldn't be hard to implement. Will do so if I find the time.

**Comment by pschmitt** [comment]
Version 0.8.0 should allow you to do this now:

```shell
obs-cli input mute "Mic/Aux"
obs-cli input unmute "Mic/Aux"
obs-cli input toggle-mute "Mic/Aux"
```

Feel free to open a new issue if it does not work as expected.
