### ISSUE TITLE
Missing item show and hide for groups of items

### ISSUE THREAD

**Issue by LigCH23** [pschmitt/obs-cli#8]
With "obs-cli item list" groups are identified.

But if we try "obs-cli item show <groupname>" there is no possibility to toggle the visibility of the group entity. It will be usefull, rather than to have to toggle each items in the group

Thanks

**Comment by pschmitt** [comment]
Done!

**Comment by LigCH23** [comment]
Hello. Thanks the modification works great. Just one remark about the error log : 
when you use
- obs-cli item show <groupname> : the item is shown, no error
- obs-cli item show -s <scenename> <groupname> : the item is shown, but the error log says "ERROR Item not found: '<groupname>' (Scene: <scenename>')

**Comment by pschmitt** [comment]
For groups you should be using `obs-cli group show/hide GROUP`

**Comment by pschmitt** [comment]
And `-s` is the shorthand for `--scene`.
Is your item named `-s`!?

**Comment by LigCH23** [comment]
sorry, i should have reread my message. 
i wrote item rather than group, and. i use html-brackets for groupname and scenename, and the info disappear in the message.

so, yes i use the right keyword "group", but when i use it with the selector -s or --scene, errors lines are displayed.

- obs-cli group show _groupname_ : the group is shown, no error
- obs-cli group show -s _scenename_ _groupname_ : the group is shown, but the error log says "ERROR Item _groupname_ not found: '' (Scene: _scenename_')
